source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIScrollView-Keyboard_Example', :exclusive => true do
  pod "UIScrollView-Keyboard", :path => "../"
end

target 'UIScrollView-Keyboard_Tests', :exclusive => true do
  pod "UIScrollView-Keyboard", :path => "../"

  
end
